# Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

# Create a Book
POST http://localhost3001/books HTTP/1.1
Content-Type: application/json

{
    "title" : "harry potter"
}

###

# Update a Book
PUT http://localhost3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title" : "Dark tower"
}

###

# Delete a Book
DELETE http://localhost3001/books/1 HTTP/1.1
Content-Type: application/json

